#!/usr/bin/env ruby

require 'osx/plist'
require 'semver'

$VERBOSE = nil

prefix = `brew --prefix 2>&1`.chomp
unless $?.success?
  msg = prefix.tr('sh:', '').strip if prefix.start_with?('sh:')
  puts msg || 'Homebrew not found or does not operate as expected. See http://brew.sh/'
  exit $?.exitstatus
end

ENV['HOMEBREW_PREFIX'] = '/usr/local'
ENV['HOMEBREW_REPOSITORY'] = '/usr/local'
ENV['HOMEBREW_LIBRARY'] = '/usr/local/Library'
ENV['HOMEBREW_CELLAR'] = '/usr/local/Cellar'
ENV['HOMEBREW_BREW_FILE'] = '/usr/local/bin/brew'

$LOAD_PATH.unshift File.join(prefix, 'Library', 'Homebrew')
require 'global'
require 'cmd/tap'

cask_tap = Tap.names.find { |tap| tap =~ /cask/ }
unless cask_tap
  abort('It seems cask is not isntalled yet. Please, see http://caskroom.io')
end
github_user, github_repo = cask_tap.split('/')

$LOAD_PATH.unshift File.join(prefix, 'Library', 'Taps', github_user, "homebrew-#{github_repo}", 'lib')
require 'hbc'

def plist_path(cask)
  app_dirs = Dir.glob(File.join(cask.caskroom_path, '*'))
    .reject { |dir| dir == cask.metadata_master_container_path }
  file = File.join(app_dirs.sort.last, app_name(cask).to_s, 'Contents', 'Info.plist')
  file if File.exist?(file)
end

def app_name(cask)
  cask.artifacts[:app].first.first unless cask.artifacts[:app].empty?
end

def current_version(file)
  return '?' unless File.exist?(file.to_s)
  plist_hash = OSX::PropertyList.load_file(file)
  plist_hash['CFBundleShortVersionString']
end

def latest_version(cask)
  cask.version.to_s
    .split('.')
    .map { |num| num[/\d+/] }
    .compact
    .join('.')
end

Hbc.installed.each do |cask|
  next if cask.installed?
  puts "#{cask} (#{current_version(plist_path(cask))} < #{latest_version(cask)})"
end
