#!/usr/bin/env ruby

require 'json'

pkg = JSON.parse( File.read('package.json') )
deps = pkg['dependencies'].merge( pkg['devDependencies'] )

deps.each do |dep, version|
  puts "#{dep}: #{version}"
end
