#!/usr/bin/env ruby

require 'json'

pkg = JSON.parse( File.read('package.json') )
deps = pkg
  .fetch('dependencies', {})
  .merge(pkg.fetch('devDependencies', {}))

deps.each do |dep, version|
  puts "#{dep}: #{version}"
end
