#!/bin/bash

# show you current system colors, cause the might looks different
# depends on configuration of used terminal application
echo -e "\033[0m COLOR_NC (No color)"
echo -e "\033[1;37m COLOR_WHITE(1;37m)  \t \033[0;30m COLOR_BLACK(0;30m)"
echo -e "\033[0;34m COLOR_BLUE(0;34m)   \t \033[1;34m COLOR_LIGHT_BLUE(1;34m)"
echo -e "\033[0;32m COLOR_GREEN(0;32m)  \t \033[1;32m COLOR_LIGHT_GREEN(1;32m)"
echo -e "\033[0;36m COLOR_CYAN(0;36m)   \t \033[1;36m COLOR_LIGHT_CYAN(1;36m)"
echo -e "\033[0;31m COLOR_RED(0;31m)    \t \033[1;31m COLOR_LIGHT_RED(1;31m)"
echo -e "\033[0;35m COLOR_PURPLE(0;35m) \t \033[1;35m COLOR_LIGHT_PURPLE(1;35m)"
echo -e "\033[0;33m COLOR_YELLOW(0;33m) \t \033[1;33m COLOR_LIGHT_YELLOW(1;33m)"
echo -e "\033[1;30m COLOR_GRAY(1;30m)   \t \033[0;37m COLOR_LIGHT_GRAY(0;37m)"
